version: "3"
services:
  reverseproxy:
    build:
        context: .
    image: sherifgamil/reverseproxy 
  backend_user:
    build:
        context: D:\General\cloud-developer-master\cloud-developer-master\course-02\exercises\udacity-c2-restapi-user
    image: sherifgamil/udacity-restapi-user
  backend_feed:
    build:
        context: D:\General\cloud-developer-master\cloud-developer-master\course-02\exercises\udacity-c2-restapi-feed  
    image: sherifgamil/udacity-restapi-feed
  frontend:
    build:
        context: D:\General\cloud-developer-master\cloud-developer-master\course-02\exercises\udacity-c2-frontend  
    image: sherifgamil/udacity-frontend