version: "3"
services:
  reverseproxy:
      image: sherifgamil/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: sherifgamil/udacity-restapi-user
    volumes:
      - C:\Users\z00465kc/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramsherifdev
      POSTGRESS_PASSWORD: udacity2020 
      POSTGRESS_DB: udagramsherifdev 
      POSTGRESS_HOST: udagramsherifdev.cbv3mymvijrk.eu-west-2.rds.amazonaws.com 
      AWS_REGION: eu-west-2 
      AWS_PROFILE: default
      AWS_BUCKET: udagram-sherif-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  backend-feed:
    image: sherifgamil/udacity-restapi-feed
    volumes:
      - C:\Users\z00465kc/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramsherifdev
      POSTGRESS_PASSWORD: udacity2020 
      POSTGRESS_DB: udagramsherifdev 
      POSTGRESS_HOST: udagramsherifdev.cbv3mymvijrk.eu-west-2.rds.amazonaws.com 
      AWS_REGION: eu-west-2 
      AWS_PROFILE: default
      AWS_BUCKET: udagram-sherif-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  frontend:
    image: sherifgamil/udacity-frontend
    ports:
      - "8100:80"